# Site settings

title: 买卖晨 － 聚宝盆
tagline: 最实用的淘指南!
email: maimaichen_admin@163.com
copyright: MaiMaiChen
keywords: open theme, github pages, semantic ui, single page apps

description: > # this means to ignore newlines until "url:". One indent required.
  Powerful new theme featuring Semantic UI for speedily creating amazing websites and mobile-hybrid apps on GitHub Pages.

# the base hostname & protocol for your site
url: "http://www.maimaichen.com"

twitter_username: maimaichen
github_username:  maimaichen

default_image: /img/opentheme-workflow.png

# Pre-processing

markdown: kramdown
highlighter: pygments
safe: true
permalink: pretty # YYYY/MM/DD/page-title/index.html
lsi: true # Lexical analysis (true) takes longer for higher quality
# sass:
#  style: :compressed

# Exclude from Jekyll processing

exclude: ["vendor", "README.md", "node_modules", "gulpfile.js", "package.json"]

# Lists

tag_items: 20     # Applies to categories and tags lists
recent_items: 10  # Applies to recent posts, apps lists
related_items: 5  # Applies to related posts and apps lists

# Layout

pagebar: false # Show (true) page sidebar menu or hide (false) 
postbar: true # Show (true) post sidebar or hide (false) 